version: '3'
services:
  app:
#    image: whoatemyapplepie/nextjsapp:0.1.0-alpha
    build:
      context: .
      dockerfile: ./nextjsapp.Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 8081:80
    volumes:
      - ./src:/app
    command: sh -c "cd ./sample-app && npm run dev"
