version: '3'
services:
  app:
    build:
      context: .
    tty: true
    ports:
      - 3000:3000
      - 8081:80
    volumes:
      - ./src:/app
    command: sh -c "cd ./sample-app && npm run dev"
